### ISSUE TITLE
syntax error with tiseanio

### ISSUE THREAD

**Issue by tiseanuser01** [bogeholm/pytisean#1]
I've downloaded pytisean to both windows and Linux versions of python.  For some reason I'm getting a syntax error with the tiseanio function.  I can't figure out why.  (I developed my own python  tisean wrapper two years ago which works fine and is an abbreviated version of yours.  I can't see any programming error on your part.)

**Comment by bogeholm** [comment]
Hello tiseanuser01,

Hmm, that sounds weird. Have you tried running the same command directly in
the terminal?

Best,
Troels

**Comment by tiseanuser01** [comment]
Good morning Troels.
 

 

The error appears as a syntax problem when I import the pytisean module. The error is triggered when it tries to process the tiseanio function.  I have embedded the python screen here.  



Python 2.7.8 (default, Jun 30 2014, 16:03:49) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> import os,sys
>>> import pytisean
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\pytisean\__init__.py", line 4, in <module>
    from .pytisean import tiseanio, tiseano
  File "C:\Python27\lib\site-packages\pytisean\pytisean.py", line 45
    def tiseanio(command, *args, data=None, silent=False):
                                    ^
SyntaxError: invalid syntax
>>>



 

 

-----Original Message-----

**Comment by bogeholm** [comment]
Goodmorning (GMT+1 :-)

I was able to reproduce your error in Python 2. I wrote the library in
Python 3, but this might not be clear from the webpage.

*In Python 2:*
Python 2.7.12 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:43:17)
[GCC 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2336.11.00)] on
darwin
>>> import pytisean
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/bogeholm/Dropbox/PhD/Python/pytisean/pytisean/__init__.py",
line 4, in <module>
    from .pytisean import tiseanio, tiseano
  File "/Users/bogeholm/Dropbox/PhD/Python/pytisean/pytisean/pytisean.py",
line 45
    def tiseanio(command, *args, data=None, silent=False):


*In Python 3:*
Python 3.5.2 |Anaconda custom (x86_64)| (default, Jul  2 2016, 17:52:12)
[GCC 4.2.1 Compatible Apple LLVM 4.2 (clang-425.0.28)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pytisean
>>>

As I am quite busy at present I will not have time to update the library -
you might be able to do that yourself as the syntax between 2 and 3 is not
that different: https://docs.python.org/3/howto/pyporting.html

I hope you are able to solve the problems!

Best regards,
Troels

**Comment by tiseanuser01** [comment]
Many thanks.  I'm embarrassed that I overlooked this.  It's a little like complaining about my laptop and failing to check to see if it was plugged in.  I very much support your effort to keep Tisean alive, and very much appreciate your patience and responsiveness in dealing with my "issue" on pytisean.  I sense that there aren't many of us who use it any more.  I do recommend it to my students, and recommend NeuroTools Tisean.  Now I will recommend your pytisean--on Python 3.    Andy Harrell, University of Alberta.







-----Original Message-----

**Comment by bogeholm** [comment]
No worries - thank you for the recommendations :-)

Cheers,
T
