### ISSUE TITLE
Proposal for multiple output handling

### ISSUE THREAD

**Issue by Ron89** [bogeholm/pytisean#3]
Hi bogeholm, nice wrapper~ It feels good to use tisean within python.

I am thinking of making it support multiple output commands. Here is a simple proposal: changing the output from
```
    [np.ndarray, msg]
```
into
```
    [dictionary={keyword:np.ndarray}, msg]
```
For single file output, keyword is simply `out`. For multiple files output, keyword would be the filetype. Since tisean wouldn't warn you about the command using multiple output. This handling need to be done command by command, so I intend to separate an `output_parser()` from function tiseanio and tiseano.

Now for legacy support, if needed (`legacy=true` by default for `output_parser()`), we can still retain command of single output to output `[np.ndarray, msg]` so that current user wouldn't be upset.

Your thoughts?

**Comment by bogeholm** [comment]
Hello Mr. Chong,

Thank you for your interest in pytisean, first and foremost! I think it's a
great idea to add support for multiple outputs.

As you suggest, a dictionary-type output might be best. I would prefer til
OrderedDict() from collections - other than that, go ahead! :-)

Best,
Troels
