### ISSUE TITLE
Syntax error invalid in Python 2.7.12

### ISSUE THREAD

**Issue by pswpswpsw** [bogeholm/pytisean#6]
```
In [2]: import pytisean
  File "pytisean/pytisean.py", line 98
    def tiseanio(command, *args, data=None, silent=False, legacy=True):
                                    ^
SyntaxError: invalid syntax
```

I installed my TISEAN on /home/shawnpan/bin , I also add this into my LD PATH, but the syntax error is really weird.

**Comment by Ron89** [comment]
Hi, currently pytisean is written with Python 3 syntax. This specifix
syntax of argument passing by reference is required differently in Python
2. See this link for detail:

https://stackoverflow.com/questions/15301999/python-2-x-default-arguments-with-args-and-kwargs

**Comment by pswpswpsw** [comment]
Thanks for the note on changing the code to Python 2!
